name: Build firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      uses: ./.github/actions/build-firmware
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: crow-${{ github.sha }}.zip
        path: crow-*/
